export enum RabbitMQ {
  CatalogQueue = 'catalog',
}

export enum ProductMSG {
  CREATE = 'CREATE_PRODUCT',
  CREATE_STOCK = 'CREATE_PROD_STOCK',
  UPDATE_STOCK = 'UPDATE_PROD_STOCK',
  FIND_ALL = 'FIND_PRODUCTS',
  FIND_ONE = 'FIND_PRODUCT',
  UPDATE = 'UPDATE_PRODUCT',
  ADD_CAT_PROD = 'ADD_CATEGORY_FROM_PRODUCT',
  DELETE = 'DELETE_PRODUCT',
  DELETE_CAT_PROD = 'DELETE_CATEGORY_FROM_PRODUCT',
}

export enum BranchMSG {
  CREATE = 'CREATE_BRANCH',
  FIND_ALL = 'FIND_BRANCHES',
  FIND_ONE = 'FIND_BRANCH',
  UPDATE = 'UPDATE_BRANCH',
  DELETE = 'DELETE_BRANCH',
}

export enum CategoryMSG {
  CREATE = 'CREATE_CATEGORY',
  FIND_ALL = 'FIND_CATEGORIES',
  FIND_ONE = 'FIND_CATEGORY',
  UPDATE = 'UPDATE_CATEGORY',
  DELETE = 'DELETE_CATEGORY',
}
